import { Suspense } from 'react'
import './globals.css'

import Nav from '@/components/navigation/Nav'
import SuspenseLoading from '@/components/shared/Loading'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <Suspense fallback={<SuspenseLoading />}>
        <body>
          {children}
          <footer>
            <Nav />
          </footer>
        </body>
      </Suspense>
    </html>
  )
}
